apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  KAFKA_URL: "my-cluster-kafka-bootstrap:9092"
  KAFKA_TOPIC: "locations"
metadata:
  name: db-env