# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\"M\n\x14LocationEventMessage\x12\x10\n\x08personId\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x02\x12\x11\n\tlongitude\x18\x03 \x01(\x02\x32I\n\x0fLocationService\x12\x36\n\x06\x43reate\x12\x15.LocationEventMessage\x1a\x15.LocationEventMessageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATIONEVENTMESSAGE._serialized_start=18
  _LOCATIONEVENTMESSAGE._serialized_end=95
  _LOCATIONSERVICE._serialized_start=97
  _LOCATIONSERVICE._serialized_end=170
# @@protoc_insertion_point(module_scope)
